// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addRoleDefault = `-- name: AddRoleDefault :exec
insert into role_defaults (role, service_id, sort) values ($1, $2, $3)
`

type AddRoleDefaultParams struct {
	Role      string      `json:"role"`
	ServiceID pgtype.UUID `json:"service_id"`
	Sort      int32       `json:"sort"`
}

func (q *Queries) AddRoleDefault(ctx context.Context, arg AddRoleDefaultParams) error {
	_, err := q.db.Exec(ctx, addRoleDefault, arg.Role, arg.ServiceID, arg.Sort)
	return err
}

const addServiceCategory = `-- name: AddServiceCategory :exec
insert into service_categories (service_id, category_id)
values ($1, $2)
on conflict do nothing
`

type AddServiceCategoryParams struct {
	ServiceID  pgtype.UUID `json:"service_id"`
	CategoryID pgtype.UUID `json:"category_id"`
}

func (q *Queries) AddServiceCategory(ctx context.Context, arg AddServiceCategoryParams) error {
	_, err := q.db.Exec(ctx, addServiceCategory, arg.ServiceID, arg.CategoryID)
	return err
}

const adminListServices = `-- name: AdminListServices :many
select id, name, description, service_url, doc_url, icon, is_active, created_at, updated_at from services order by name
`

// Full catalog including soft-deleted (inactive) services.
func (q *Queries) AdminListServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.Query(ctx, adminListServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ServiceUrl,
			&i.DocUrl,
			&i.Icon,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createCategory = `-- name: CreateCategory :one
insert into categories (slug, label, sort) values ($1, $2, $3) returning id, slug, label, sort
`

type CreateCategoryParams struct {
	Slug  string `json:"slug"`
	Label []byte `json:"label"`
	Sort  int32  `json:"sort"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.Slug, arg.Label, arg.Sort)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Label,
		&i.Sort,
	)
	return i, err
}

const createService = `-- name: CreateService :one
insert into services (name, description, service_url, doc_url, icon)
values ($1, $2, $3, $4, $5)
returning id, name, description, service_url, doc_url, icon, is_active, created_at, updated_at
`

type CreateServiceParams struct {
	Name        string      `json:"name"`
	Description []byte      `json:"description"`
	ServiceUrl  pgtype.Text `json:"service_url"`
	DocUrl      pgtype.Text `json:"doc_url"`
	Icon        string      `json:"icon"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createService,
		arg.Name,
		arg.Description,
		arg.ServiceUrl,
		arg.DocUrl,
		arg.Icon,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ServiceUrl,
		&i.DocUrl,
		&i.Icon,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRoleDefaults = `-- name: DeleteRoleDefaults :exec
delete from role_defaults where role = $1
`

func (q *Queries) DeleteRoleDefaults(ctx context.Context, role string) error {
	_, err := q.db.Exec(ctx, deleteRoleDefaults, role)
	return err
}

const deleteServiceCategories = `-- name: DeleteServiceCategories :exec
delete from service_categories where service_id = $1
`

func (q *Queries) DeleteServiceCategories(ctx context.Context, serviceID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteServiceCategories, serviceID)
	return err
}

const getCategoryBySlug = `-- name: GetCategoryBySlug :one
select id, slug, label, sort from categories where slug = $1
`

func (q *Queries) GetCategoryBySlug(ctx context.Context, slug string) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryBySlug, slug)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Label,
		&i.Sort,
	)
	return i, err
}

const getServiceByID = `-- name: GetServiceByID :one
select id, name, description, service_url, doc_url, icon, is_active, created_at, updated_at from services where id = $1
`

func (q *Queries) GetServiceByID(ctx context.Context, id pgtype.UUID) (Service, error) {
	row := q.db.QueryRow(ctx, getServiceByID, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ServiceUrl,
		&i.DocUrl,
		&i.Icon,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAudit = `-- name: InsertAudit :exec
insert into audit_log (actor_id, actor_kind, action, target_id, diff)
values ($1, $2, $3, $4, $5)
`

type InsertAuditParams struct {
	ActorID   pgtype.UUID `json:"actor_id"`
	ActorKind string      `json:"actor_kind"`
	Action    string      `json:"action"`
	TargetID  pgtype.UUID `json:"target_id"`
	Diff      []byte      `json:"diff"`
}

func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) error {
	_, err := q.db.Exec(ctx, insertAudit,
		arg.ActorID,
		arg.ActorKind,
		arg.Action,
		arg.TargetID,
		arg.Diff,
	)
	return err
}

const listAudit = `-- name: ListAudit :many
select id, actor_id, actor_kind, action, target_id, diff, created_at from audit_log order by created_at desc limit $1
`

func (q *Queries) ListAudit(ctx context.Context, lim int32) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAudit, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.ActorKind,
			&i.Action,
			&i.TargetID,
			&i.Diff,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceCategorySlugs = `-- name: ListServiceCategorySlugs :many
select c.slug
from service_categories sc
join categories c on c.id = sc.category_id
where sc.service_id = $1
order by c.slug
`

func (q *Queries) ListServiceCategorySlugs(ctx context.Context, serviceID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listServiceCategorySlugs, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var slug string
		if err := rows.Scan(&slug); err != nil {
			return nil, err
		}
		items = append(items, slug)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteService = `-- name: SoftDeleteService :execrows
update services set is_active = false, updated_at = now() where id = $1 and is_active = true
`

func (q *Queries) SoftDeleteService(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteService, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateService = `-- name: UpdateService :one
update services
set name        = $1,
    description = $2,
    service_url = $3,
    doc_url     = $4,
    icon        = $5,
    updated_at  = now()
where id = $6
returning id, name, description, service_url, doc_url, icon, is_active, created_at, updated_at
`

type UpdateServiceParams struct {
	Name        string      `json:"name"`
	Description []byte      `json:"description"`
	ServiceUrl  pgtype.Text `json:"service_url"`
	DocUrl      pgtype.Text `json:"doc_url"`
	Icon        string      `json:"icon"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, updateService,
		arg.Name,
		arg.Description,
		arg.ServiceUrl,
		arg.DocUrl,
		arg.Icon,
		arg.ID,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ServiceUrl,
		&i.DocUrl,
		&i.Icon,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
