// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: announce.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminListAnnouncements = `-- name: AdminListAnnouncements :many
select id, title, body, severity, audience, starts_at, ends_at, dismissible, created_by, created_at from announcements order by created_at desc limit $1
`

func (q *Queries) AdminListAnnouncements(ctx context.Context, lim int32) ([]Announcement, error) {
	rows, err := q.db.Query(ctx, adminListAnnouncements, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Announcement{}
	for rows.Next() {
		var i Announcement
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.Severity,
			&i.Audience,
			&i.StartsAt,
			&i.EndsAt,
			&i.Dismissible,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAnnouncements = `-- name: CountAnnouncements :one
select count(*) from announcements
`

func (q *Queries) CountAnnouncements(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAnnouncements)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAnnouncement = `-- name: CreateAnnouncement :one
insert into announcements (title, body, severity, audience, starts_at, ends_at, dismissible, created_by)
values ($1, $2, $3, $4, $5, $6, $7, $8)
returning id, title, body, severity, audience, starts_at, ends_at, dismissible, created_by, created_at
`

type CreateAnnouncementParams struct {
	Title       []byte             `json:"title"`
	Body        []byte             `json:"body"`
	Severity    string             `json:"severity"`
	Audience    string             `json:"audience"`
	StartsAt    pgtype.Timestamptz `json:"starts_at"`
	EndsAt      pgtype.Timestamptz `json:"ends_at"`
	Dismissible bool               `json:"dismissible"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
}

func (q *Queries) CreateAnnouncement(ctx context.Context, arg CreateAnnouncementParams) (Announcement, error) {
	row := q.db.QueryRow(ctx, createAnnouncement,
		arg.Title,
		arg.Body,
		arg.Severity,
		arg.Audience,
		arg.StartsAt,
		arg.EndsAt,
		arg.Dismissible,
		arg.CreatedBy,
	)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Severity,
		&i.Audience,
		&i.StartsAt,
		&i.EndsAt,
		&i.Dismissible,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAnnouncement = `-- name: DeleteAnnouncement :execrows
delete from announcements where id = $1
`

func (q *Queries) DeleteAnnouncement(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAnnouncement, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const dismissAnnouncement = `-- name: DismissAnnouncement :exec
insert into announcement_dismissals (user_id, announcement_id)
values ($1, $2)
on conflict (user_id, announcement_id) do nothing
`

type DismissAnnouncementParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	AnnouncementID pgtype.UUID `json:"announcement_id"`
}

// Record a per-user dismissal. Idempotent: dismissing twice is a no-op.
func (q *Queries) DismissAnnouncement(ctx context.Context, arg DismissAnnouncementParams) error {
	_, err := q.db.Exec(ctx, dismissAnnouncement, arg.UserID, arg.AnnouncementID)
	return err
}

const getAnnouncementByID = `-- name: GetAnnouncementByID :one
select id, title, body, severity, audience, starts_at, ends_at, dismissible, created_by, created_at from announcements where id = $1
`

func (q *Queries) GetAnnouncementByID(ctx context.Context, id pgtype.UUID) (Announcement, error) {
	row := q.db.QueryRow(ctx, getAnnouncementByID, id)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Severity,
		&i.Audience,
		&i.StartsAt,
		&i.EndsAt,
		&i.Dismissible,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveAnnouncements = `-- name: ListActiveAnnouncements :many
select a.id, a.title, a.body, a.severity, a.audience, a.starts_at, a.ends_at, a.dismissible, a.created_by, a.created_at
from announcements a
where (a.starts_at is null or a.starts_at <= now())
  and (a.ends_at is null or a.ends_at > now())
  and (a.audience = 'all' or a.audience = $1)
  and not exists (
    select 1 from announcement_dismissals d
    where d.announcement_id = a.id and d.user_id = $2
  )
order by case a.severity when 'critical' then 0 when 'warning' then 1 else 2 end, a.created_at desc
`

type ListActiveAnnouncementsParams struct {
	Role   string      `json:"role"`
	UserID pgtype.UUID `json:"user_id"`
}

// Active = within its time window, addressed to the user's role (or all), and
// not already dismissed by the user, most-severe first (docs/01 §4.7).
func (q *Queries) ListActiveAnnouncements(ctx context.Context, arg ListActiveAnnouncementsParams) ([]Announcement, error) {
	rows, err := q.db.Query(ctx, listActiveAnnouncements, arg.Role, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Announcement{}
	for rows.Next() {
		var i Announcement
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.Severity,
			&i.Audience,
			&i.StartsAt,
			&i.EndsAt,
			&i.Dismissible,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllActiveAnnouncements = `-- name: ListAllActiveAnnouncements :many
select id, title, body, severity, audience, starts_at, ends_at, dismissible, created_by, created_at
from announcements
where (starts_at is null or starts_at <= now())
  and (ends_at is null or ends_at > now())
order by case severity when 'critical' then 0 when 'warning' then 1 else 2 end, created_at desc
`

// Active = within its time window, across ALL audiences. For the public,
// identity-less catalog MCP server, which has no user role to filter on and
// must not hide a maintenance notice addressed to a specific role.
func (q *Queries) ListAllActiveAnnouncements(ctx context.Context) ([]Announcement, error) {
	rows, err := q.db.Query(ctx, listAllActiveAnnouncements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Announcement{}
	for rows.Next() {
		var i Announcement
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.Severity,
			&i.Audience,
			&i.StartsAt,
			&i.EndsAt,
			&i.Dismissible,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnnouncementHistory = `-- name: ListAnnouncementHistory :many
select a.id, a.title, a.body, a.severity, a.audience, a.starts_at, a.ends_at, a.dismissible, a.created_by, a.created_at
from announcements a
where (a.starts_at is null or a.starts_at <= now())
  and (a.audience = 'all' or a.audience = $1)
  and (
    (a.ends_at is not null and a.ends_at <= now())
    or exists (
      select 1 from announcement_dismissals d
      where d.announcement_id = a.id and d.user_id = $2
    )
  )
order by a.created_at desc
limit $3
`

type ListAnnouncementHistoryParams struct {
	Role   string      `json:"role"`
	UserID pgtype.UUID `json:"user_id"`
	Lim    int32       `json:"lim"`
}

// A user's past notices for the notification center: addressed to their role (or
// all), already started, and no longer an active banner for them — either the
// window has ended OR they dismissed it. Most recent first.
func (q *Queries) ListAnnouncementHistory(ctx context.Context, arg ListAnnouncementHistoryParams) ([]Announcement, error) {
	rows, err := q.db.Query(ctx, listAnnouncementHistory, arg.Role, arg.UserID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Announcement{}
	for rows.Next() {
		var i Announcement
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.Severity,
			&i.Audience,
			&i.StartsAt,
			&i.EndsAt,
			&i.Dismissible,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeAnnouncementsBefore = `-- name: PurgeAnnouncementsBefore :execrows
delete from announcements
where coalesce(starts_at, created_at) < $1
  and ends_at is not null
  and ends_at <= now()
`

// Permanently delete expired announcements that started before the retention
// cutoff (history retention; dismissals cascade away). Only expired notices are
// purged, so an active banner is never removed regardless of age. starts_at may
// be null for notices shown immediately, so fall back to created_at.
func (q *Queries) PurgeAnnouncementsBefore(ctx context.Context, cutoff pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, purgeAnnouncementsBefore, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retireActiveAnnouncements = `-- name: RetireActiveAnnouncements :exec
update announcements
set ends_at = now()
where (starts_at is null or starts_at <= now())
  and (ends_at is null or ends_at > now())
`

// Close any currently-active announcement by ending its window now. Called when
// a new announcement is created so there is at most one active notice at a time,
// while the retired one stays in the table as history (docs/01 §4.7).
func (q *Queries) RetireActiveAnnouncements(ctx context.Context) error {
	_, err := q.db.Exec(ctx, retireActiveAnnouncements)
	return err
}

const updateAnnouncement = `-- name: UpdateAnnouncement :one
update announcements
set title       = $1,
    body        = $2,
    severity    = $3,
    audience    = $4,
    starts_at   = $5,
    ends_at     = $6,
    dismissible = $7
where id = $8
returning id, title, body, severity, audience, starts_at, ends_at, dismissible, created_by, created_at
`

type UpdateAnnouncementParams struct {
	Title       []byte             `json:"title"`
	Body        []byte             `json:"body"`
	Severity    string             `json:"severity"`
	Audience    string             `json:"audience"`
	StartsAt    pgtype.Timestamptz `json:"starts_at"`
	EndsAt      pgtype.Timestamptz `json:"ends_at"`
	Dismissible bool               `json:"dismissible"`
	ID          pgtype.UUID        `json:"id"`
}

func (q *Queries) UpdateAnnouncement(ctx context.Context, arg UpdateAnnouncementParams) (Announcement, error) {
	row := q.db.QueryRow(ctx, updateAnnouncement,
		arg.Title,
		arg.Body,
		arg.Severity,
		arg.Audience,
		arg.StartsAt,
		arg.EndsAt,
		arg.Dismissible,
		arg.ID,
	)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Severity,
		&i.Audience,
		&i.StartsAt,
		&i.EndsAt,
		&i.Dismissible,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
