// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: announce.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminListAnnouncements = `-- name: AdminListAnnouncements :many
select id, title, body, severity, audience, starts_at, ends_at, dismissible, created_by, created_at from announcements order by created_at desc limit $1
`

func (q *Queries) AdminListAnnouncements(ctx context.Context, lim int32) ([]Announcement, error) {
	rows, err := q.db.Query(ctx, adminListAnnouncements, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Announcement{}
	for rows.Next() {
		var i Announcement
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.Severity,
			&i.Audience,
			&i.StartsAt,
			&i.EndsAt,
			&i.Dismissible,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAnnouncement = `-- name: CreateAnnouncement :one
insert into announcements (title, body, severity, audience, starts_at, ends_at, dismissible, created_by)
values ($1, $2, $3, $4, $5, $6, $7, $8)
returning id, title, body, severity, audience, starts_at, ends_at, dismissible, created_by, created_at
`

type CreateAnnouncementParams struct {
	Title       []byte             `json:"title"`
	Body        []byte             `json:"body"`
	Severity    string             `json:"severity"`
	Audience    string             `json:"audience"`
	StartsAt    pgtype.Timestamptz `json:"starts_at"`
	EndsAt      pgtype.Timestamptz `json:"ends_at"`
	Dismissible bool               `json:"dismissible"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
}

func (q *Queries) CreateAnnouncement(ctx context.Context, arg CreateAnnouncementParams) (Announcement, error) {
	row := q.db.QueryRow(ctx, createAnnouncement,
		arg.Title,
		arg.Body,
		arg.Severity,
		arg.Audience,
		arg.StartsAt,
		arg.EndsAt,
		arg.Dismissible,
		arg.CreatedBy,
	)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Severity,
		&i.Audience,
		&i.StartsAt,
		&i.EndsAt,
		&i.Dismissible,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getAnnouncementByID = `-- name: GetAnnouncementByID :one
select id, title, body, severity, audience, starts_at, ends_at, dismissible, created_by, created_at from announcements where id = $1
`

func (q *Queries) GetAnnouncementByID(ctx context.Context, id pgtype.UUID) (Announcement, error) {
	row := q.db.QueryRow(ctx, getAnnouncementByID, id)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Severity,
		&i.Audience,
		&i.StartsAt,
		&i.EndsAt,
		&i.Dismissible,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveAnnouncements = `-- name: ListActiveAnnouncements :many
select id, title, body, severity, audience, starts_at, ends_at, dismissible, created_by, created_at
from announcements
where (starts_at is null or starts_at <= now())
  and (ends_at is null or ends_at > now())
  and (audience = 'all' or audience = $1)
order by case severity when 'critical' then 0 when 'warning' then 1 else 2 end, created_at desc
`

// Active = within its time window and addressed to the user's role (or all),
// most-severe first (docs/01 §4.7).
func (q *Queries) ListActiveAnnouncements(ctx context.Context, role string) ([]Announcement, error) {
	rows, err := q.db.Query(ctx, listActiveAnnouncements, role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Announcement{}
	for rows.Next() {
		var i Announcement
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.Severity,
			&i.Audience,
			&i.StartsAt,
			&i.EndsAt,
			&i.Dismissible,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAnnouncement = `-- name: UpdateAnnouncement :one
update announcements
set title       = $1,
    body        = $2,
    severity    = $3,
    audience    = $4,
    starts_at   = $5,
    ends_at     = $6,
    dismissible = $7
where id = $8
returning id, title, body, severity, audience, starts_at, ends_at, dismissible, created_by, created_at
`

type UpdateAnnouncementParams struct {
	Title       []byte             `json:"title"`
	Body        []byte             `json:"body"`
	Severity    string             `json:"severity"`
	Audience    string             `json:"audience"`
	StartsAt    pgtype.Timestamptz `json:"starts_at"`
	EndsAt      pgtype.Timestamptz `json:"ends_at"`
	Dismissible bool               `json:"dismissible"`
	ID          pgtype.UUID        `json:"id"`
}

func (q *Queries) UpdateAnnouncement(ctx context.Context, arg UpdateAnnouncementParams) (Announcement, error) {
	row := q.db.QueryRow(ctx, updateAnnouncement,
		arg.Title,
		arg.Body,
		arg.Severity,
		arg.Audience,
		arg.StartsAt,
		arg.EndsAt,
		arg.Dismissible,
		arg.ID,
	)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Severity,
		&i.Audience,
		&i.StartsAt,
		&i.EndsAt,
		&i.Dismissible,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
