// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRoleDefaults = `-- name: GetRoleDefaults :many
select rd.service_id
from role_defaults rd
join services s on s.id = rd.service_id
where rd.role = $1 and s.is_active = true
order by rd.sort, s.name
`

// Active services in the admin-curated order for a role (docs/01 §3).
func (q *Queries) GetRoleDefaults(ctx context.Context, role string) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getRoleDefaults, role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var service_id pgtype.UUID
		if err := rows.Scan(&service_id); err != nil {
			return nil, err
		}
		items = append(items, service_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveServiceCategories = `-- name: ListActiveServiceCategories :many
select sc.service_id, c.slug
from service_categories sc
join categories c on c.id = sc.category_id
join services s on s.id = sc.service_id
where s.is_active = true
`

type ListActiveServiceCategoriesRow struct {
	ServiceID pgtype.UUID `json:"service_id"`
	Slug      string      `json:"slug"`
}

// (service_id, category slug) pairs for active services, to assemble the
// many-to-many in Go when building the catalog snapshot.
func (q *Queries) ListActiveServiceCategories(ctx context.Context) ([]ListActiveServiceCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listActiveServiceCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveServiceCategoriesRow{}
	for rows.Next() {
		var i ListActiveServiceCategoriesRow
		if err := rows.Scan(&i.ServiceID, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveServices = `-- name: ListActiveServices :many
select id, name, description, service_url, doc_url, icon, tag
from services
where is_active = true
order by name
`

type ListActiveServicesRow struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description []byte      `json:"description"`
	ServiceUrl  pgtype.Text `json:"service_url"`
	DocUrl      pgtype.Text `json:"doc_url"`
	Icon        string      `json:"icon"`
	Tag         pgtype.Text `json:"tag"`
}

// Note: keywords are intentionally NOT selected — they are a search-only aid
// matched in SQL (search.sql), never exposed via /api/catalog.
func (q *Queries) ListActiveServices(ctx context.Context) ([]ListActiveServicesRow, error) {
	rows, err := q.db.Query(ctx, listActiveServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveServicesRow{}
	for rows.Next() {
		var i ListActiveServicesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ServiceUrl,
			&i.DocUrl,
			&i.Icon,
			&i.Tag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
select id, slug, label, sort from categories order by sort, slug
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Label,
			&i.Sort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
