// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package store

import (
	"context"
)

const countCategories = `-- name: CountCategories :one
select count(*) from categories
`

// A trivial query used in Phase 0 to prove the sqlc -> pgx pipeline end-to-end.
// Real catalog queries arrive in Phase 1.
func (q *Queries) CountCategories(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCategories)
	var count int64
	err := row.Scan(&count)
	return count, err
}
