// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: favorites.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addFavorite = `-- name: AddFavorite :exec
insert into favorites (user_id, service_id, sort)
values ($1, $2, $3)
on conflict (user_id, service_id) do nothing
`

type AddFavoriteParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ServiceID pgtype.UUID `json:"service_id"`
	Sort      int32       `json:"sort"`
}

func (q *Queries) AddFavorite(ctx context.Context, arg AddFavoriteParams) error {
	_, err := q.db.Exec(ctx, addFavorite, arg.UserID, arg.ServiceID, arg.Sort)
	return err
}

const listFavoriteServiceIDs = `-- name: ListFavoriteServiceIDs :many
select service_id from favorites where user_id = $1 order by sort, created_at
`

func (q *Queries) ListFavoriteServiceIDs(ctx context.Context, userID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listFavoriteServiceIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var service_id pgtype.UUID
		if err := rows.Scan(&service_id); err != nil {
			return nil, err
		}
		items = append(items, service_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextFavoriteSort = `-- name: NextFavoriteSort :one
select coalesce(max(sort) + 1, 0)::int from favorites where user_id = $1
`

func (q *Queries) NextFavoriteSort(ctx context.Context, userID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextFavoriteSort, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const removeFavorite = `-- name: RemoveFavorite :execrows
delete from favorites where user_id = $1 and service_id = $2
`

type RemoveFavoriteParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ServiceID pgtype.UUID `json:"service_id"`
}

func (q *Queries) RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeFavorite, arg.UserID, arg.ServiceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
