// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metrics.sql

package store

import (
	"context"
)

const countActiveAnnouncementsBySeverity = `-- name: CountActiveAnnouncementsBySeverity :many
select severity, count(*) as n
from announcements
where (starts_at is null or starts_at <= now())
  and (ends_at is null or ends_at > now())
group by severity
`

type CountActiveAnnouncementsBySeverityRow struct {
	Severity string `json:"severity"`
	N        int64  `json:"n"`
}

func (q *Queries) CountActiveAnnouncementsBySeverity(ctx context.Context) ([]CountActiveAnnouncementsBySeverityRow, error) {
	rows, err := q.db.Query(ctx, countActiveAnnouncementsBySeverity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountActiveAnnouncementsBySeverityRow{}
	for rows.Next() {
		var i CountActiveAnnouncementsBySeverityRow
		if err := rows.Scan(&i.Severity, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countActiveSessions = `-- name: CountActiveSessions :one
select count(*) from sessions where expires_at > now()
`

func (q *Queries) CountActiveSessions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSessions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFavoritesByService = `-- name: CountFavoritesByService :many
select s.name, count(f.user_id) as n
from services s
left join favorites f on f.service_id = s.id
where s.is_active = true
group by s.name
`

type CountFavoritesByServiceRow struct {
	Name string `json:"name"`
	N    int64  `json:"n"`
}

// Favorites per active service. The left join keeps a service nobody has
// pinned in the result with n = 0, so its gauge series exists rather than
// silently dropping out of the dashboard.
func (q *Queries) CountFavoritesByService(ctx context.Context) ([]CountFavoritesByServiceRow, error) {
	rows, err := q.db.Query(ctx, countFavoritesByService)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountFavoritesByServiceRow{}
	for rows.Next() {
		var i CountFavoritesByServiceRow
		if err := rows.Scan(&i.Name, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countServicesByState = `-- name: CountServicesByState :many
select is_active, count(*) as n from services group by is_active
`

type CountServicesByStateRow struct {
	IsActive bool  `json:"is_active"`
	N        int64 `json:"n"`
}

func (q *Queries) CountServicesByState(ctx context.Context) ([]CountServicesByStateRow, error) {
	rows, err := q.db.Query(ctx, countServicesByState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountServicesByStateRow{}
	for rows.Next() {
		var i CountServicesByStateRow
		if err := rows.Scan(&i.IsActive, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
