// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metrics.sql

package store

import (
	"context"
)

const countActiveAnnouncementsBySeverity = `-- name: CountActiveAnnouncementsBySeverity :many
select severity, count(*) as n
from announcements
where (starts_at is null or starts_at <= now())
  and (ends_at is null or ends_at > now())
group by severity
`

type CountActiveAnnouncementsBySeverityRow struct {
	Severity string `json:"severity"`
	N        int64  `json:"n"`
}

func (q *Queries) CountActiveAnnouncementsBySeverity(ctx context.Context) ([]CountActiveAnnouncementsBySeverityRow, error) {
	rows, err := q.db.Query(ctx, countActiveAnnouncementsBySeverity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountActiveAnnouncementsBySeverityRow{}
	for rows.Next() {
		var i CountActiveAnnouncementsBySeverityRow
		if err := rows.Scan(&i.Severity, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countActiveSessions = `-- name: CountActiveSessions :one
select count(*) from sessions where expires_at > now()
`

func (q *Queries) CountActiveSessions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSessions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFavoritesByServiceAndRole = `-- name: CountFavoritesByServiceAndRole :many
select s.name, r.role::text as role, 0::bigint as n
from services s
cross join unnest($1::text[]) as r(role)
where s.is_active = true
union all
select s.name, u.primary_role as role, count(*) as n
from favorites f
join users u on u.id = f.user_id
join services s on s.id = f.service_id
where s.is_active = true
group by s.name, u.primary_role
`

type CountFavoritesByServiceAndRoleRow struct {
	Name string `json:"name"`
	Role string `json:"role"`
	N    int64  `json:"n"`
}

// Favorites per active service and configured role. Two branches:
//
//  1. The cross join of active services with the configured role list emits a
//     zero for every (service × role) pair, so a service nobody pinned — or a
//     role that pinned nothing — keeps its series instead of dropping out of
//     the dashboard (#128's deliberate property, now in two dimensions).
//  2. The actual counts, grouped by the role as stored on the user. Roles the
//     config no longer defines come back verbatim; the caller folds them onto
//     the configured default (internal/metrics), which keeps the "effective
//     role" rule in one place — config.RoleSet.Effective — rather than
//     duplicating it here as a second parameter and a case expression.
//
// A (service, role) pair therefore appears more than once and the caller sums;
// the zero rows are the additive identity that makes that safe.
func (q *Queries) CountFavoritesByServiceAndRole(ctx context.Context, roles []string) ([]CountFavoritesByServiceAndRoleRow, error) {
	rows, err := q.db.Query(ctx, countFavoritesByServiceAndRole, roles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountFavoritesByServiceAndRoleRow{}
	for rows.Next() {
		var i CountFavoritesByServiceAndRoleRow
		if err := rows.Scan(&i.Name, &i.Role, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countServicesByState = `-- name: CountServicesByState :many
select is_active, count(*) as n from services group by is_active
`

type CountServicesByStateRow struct {
	IsActive bool  `json:"is_active"`
	N        int64 `json:"n"`
}

func (q *Queries) CountServicesByState(ctx context.Context) ([]CountServicesByStateRow, error) {
	rows, err := q.db.Query(ctx, countServicesByState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountServicesByStateRow{}
	for rows.Next() {
		var i CountServicesByStateRow
		if err := rows.Scan(&i.IsActive, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
