// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID    pgtype.UUID `json:"id"`
	Slug  string      `json:"slug"`
	Label []byte      `json:"label"`
	Sort  int32       `json:"sort"`
}

type RoleDefault struct {
	Role      string      `json:"role"`
	ServiceID pgtype.UUID `json:"service_id"`
	Sort      int32       `json:"sort"`
}

type Service struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description []byte             `json:"description"`
	ServiceUrl  pgtype.Text        `json:"service_url"`
	DocUrl      pgtype.Text        `json:"doc_url"`
	Icon        string             `json:"icon"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ServiceCategory struct {
	ServiceID  pgtype.UUID `json:"service_id"`
	CategoryID pgtype.UUID `json:"category_id"`
}

type Session struct {
	ID        string             `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Data      []byte             `json:"data"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type User struct {
	ID          pgtype.UUID        `json:"id"`
	OidcSub     string             `json:"oidc_sub"`
	DisplayName string             `json:"display_name"`
	Email       pgtype.Text        `json:"email"`
	PrimaryRole string             `json:"primary_role"`
	IsAdmin     bool               `json:"is_admin"`
	ViewMode    string             `json:"view_mode"`
	Theme       string             `json:"theme"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	LastSeenAt  pgtype.Timestamptz `json:"last_seen_at"`
}
