// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Announcement struct {
	ID          pgtype.UUID        `json:"id"`
	Title       []byte             `json:"title"`
	Body        []byte             `json:"body"`
	Severity    string             `json:"severity"`
	Audience    string             `json:"audience"`
	StartsAt    pgtype.Timestamptz `json:"starts_at"`
	EndsAt      pgtype.Timestamptz `json:"ends_at"`
	Dismissible bool               `json:"dismissible"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type AnnouncementDismissal struct {
	UserID         pgtype.UUID        `json:"user_id"`
	AnnouncementID pgtype.UUID        `json:"announcement_id"`
	DismissedAt    pgtype.Timestamptz `json:"dismissed_at"`
}

type AuditLog struct {
	ID        int64              `json:"id"`
	ActorID   pgtype.UUID        `json:"actor_id"`
	ActorKind string             `json:"actor_kind"`
	Action    string             `json:"action"`
	TargetID  pgtype.UUID        `json:"target_id"`
	Diff      []byte             `json:"diff"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Category struct {
	ID    pgtype.UUID `json:"id"`
	Slug  string      `json:"slug"`
	Label []byte      `json:"label"`
	Sort  int32       `json:"sort"`
}

type ClickEvent struct {
	ID        int64              `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	ServiceID pgtype.UUID        `json:"service_id"`
	UserRole  string             `json:"user_role"`
	ClickedAt pgtype.Timestamptz `json:"clicked_at"`
	Target    string             `json:"target"`
}

type Favorite struct {
	UserID    pgtype.UUID        `json:"user_id"`
	ServiceID pgtype.UUID        `json:"service_id"`
	Sort      int32              `json:"sort"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RoleDefault struct {
	Role      string      `json:"role"`
	ServiceID pgtype.UUID `json:"service_id"`
	Sort      int32       `json:"sort"`
}

type Service struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description []byte             `json:"description"`
	ServiceUrl  pgtype.Text        `json:"service_url"`
	DocUrl      pgtype.Text        `json:"doc_url"`
	Icon        string             `json:"icon"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Tag         pgtype.Text        `json:"tag"`
}

type ServiceCategory struct {
	ServiceID  pgtype.UUID `json:"service_id"`
	CategoryID pgtype.UUID `json:"category_id"`
}

type Session struct {
	ID        string             `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Data      []byte             `json:"data"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type UsageDaily struct {
	Day       pgtype.Date `json:"day"`
	ServiceID pgtype.UUID `json:"service_id"`
	UserRole  string      `json:"user_role"`
	Clicks    int64       `json:"clicks"`
	Target    string      `json:"target"`
}

type User struct {
	ID                   pgtype.UUID        `json:"id"`
	OidcSub              string             `json:"oidc_sub"`
	DisplayName          string             `json:"display_name"`
	Email                pgtype.Text        `json:"email"`
	PrimaryRole          string             `json:"primary_role"`
	IsAdmin              bool               `json:"is_admin"`
	ViewMode             string             `json:"view_mode"`
	Theme                string             `json:"theme"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	LastSeenAt           pgtype.Timestamptz `json:"last_seen_at"`
	FavoritesOrder       string             `json:"favorites_order"`
	FavoritesSeparateTab bool               `json:"favorites_separate_tab"`
	FavoritesSeeded      bool               `json:"favorites_seeded"`
	Locale               string             `json:"locale"`
}
