// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddFavorite(ctx context.Context, arg AddFavoriteParams) error
	AddRoleDefault(ctx context.Context, arg AddRoleDefaultParams) error
	AddServiceCategory(ctx context.Context, arg AddServiceCategoryParams) error
	AdminListAnnouncements(ctx context.Context, lim int32) ([]Announcement, error)
	// Full catalog including soft-deleted (inactive) services.
	AdminListServices(ctx context.Context) ([]Service, error)
	CountActiveAnnouncementsBySeverity(ctx context.Context) ([]CountActiveAnnouncementsBySeverityRow, error)
	CountActiveSessions(ctx context.Context) (int64, error)
	// A trivial query used in Phase 0 to prove the sqlc -> pgx pipeline end-to-end.
	// Real catalog queries arrive in Phase 1.
	CountCategories(ctx context.Context) (int64, error)
	CountServicesByState(ctx context.Context) ([]CountServicesByStateRow, error)
	CreateAnnouncement(ctx context.Context, arg CreateAnnouncementParams) (Announcement, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateService(ctx context.Context, arg CreateServiceParams) (Service, error)
	// id is sha256(token); the raw token lives only in the cookie, so a DB read
	// never yields a usable session credential.
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteRoleDefaults(ctx context.Context, role string) error
	DeleteServiceCategories(ctx context.Context, serviceID pgtype.UUID) error
	DeleteSession(ctx context.Context, id string) error
	// The user's most-clicked active services within a rolling window, most-used
	// first (powers "frequently used" — docs/01 §4.5). Launches only (target =
	// 'service'); a documentation-link click shouldn't promote a service here.
	FrequentServiceIDs(ctx context.Context, arg FrequentServiceIDsParams) ([]pgtype.UUID, error)
	GetAnnouncementByID(ctx context.Context, id pgtype.UUID) (Announcement, error)
	GetCategoryBySlug(ctx context.Context, slug string) (Category, error)
	// Active services in the admin-curated order for a role (docs/01 §3).
	GetRoleDefaults(ctx context.Context, role string) ([]pgtype.UUID, error)
	GetServiceByID(ctx context.Context, id pgtype.UUID) (Service, error)
	GetSession(ctx context.Context, id string) (Session, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserBySub(ctx context.Context, oidcSub string) (User, error)
	InsertAudit(ctx context.Context, arg InsertAuditParams) error
	// Active = within its time window and addressed to the user's role (or all),
	// most-severe first (docs/01 §4.7).
	ListActiveAnnouncements(ctx context.Context, role string) ([]Announcement, error)
	// (service_id, category slug) pairs for active services, to assemble the
	// many-to-many in Go when building the catalog snapshot.
	ListActiveServiceCategories(ctx context.Context) ([]ListActiveServiceCategoriesRow, error)
	ListActiveServices(ctx context.Context) ([]ListActiveServicesRow, error)
	// Active = within its time window, across ALL audiences. For the public,
	// identity-less catalog MCP server, which has no user role to filter on and
	// must not hide a maintenance notice addressed to a specific role.
	ListAllActiveAnnouncements(ctx context.Context) ([]Announcement, error)
	// LEFT JOIN so rows whose actor_id is null (MCP/system, or no user) still list;
	// actor_name resolves the acting user for the admin audit view.
	ListAudit(ctx context.Context, lim int32) ([]ListAuditRow, error)
	ListCategories(ctx context.Context) ([]Category, error)
	// Favorites ordered alphabetically by service name.
	ListFavoritesAlpha(ctx context.Context, userID pgtype.UUID) ([]pgtype.UUID, error)
	// Favorites ordered by the user's click count (most-used first), then by the
	// stored order as a stable tiebreaker.
	ListFavoritesByUsage(ctx context.Context, userID pgtype.UUID) ([]pgtype.UUID, error)
	ListServiceCategorySlugs(ctx context.Context, serviceID pgtype.UUID) ([]string, error)
	MarkFavoritesSeeded(ctx context.Context, userID pgtype.UUID) error
	NextFavoriteSort(ctx context.Context, userID pgtype.UUID) (int32, error)
	PurgeOldClicks(ctx context.Context, cutoff pgtype.Timestamptz) (int64, error)
	// A lightweight click event (docs/01 §5.4). user_role is denormalized so
	// aggregate metrics (Phase 4) need no join. target distinguishes a launch
	// ('service') from a documentation-link click ('documentation'). NULLs on
	// user/service delete keep history intact when a user or service is removed.
	RecordClick(ctx context.Context, arg RecordClickParams) error
	RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) (int64, error)
	// Recompute usage_daily from the raw events still present (the retention
	// window). Idempotent: SET (not add). Days whose raw events have been purged are
	// no longer recomputed, so their aggregate rows stay frozen at their last value.
	RollupClicks(ctx context.Context) error
	// Fuzzy/substring search over name, localized descriptions, and category labels
	// (docs/01 §4.6, docs/02 §5). Returns active service ids ranked by name
	// similarity then name. Categories are attached from the catalog snapshot in the
	// handler, so the result shape matches /api/catalog.
	SearchServiceIDs(ctx context.Context, q_ pgtype.Text) ([]pgtype.UUID, error)
	// One-time pre-fill: copy the user's role defaults into favorites as real,
	// editable entries (concept §4.4).
	SeedFavoritesFromRoleDefaults(ctx context.Context, arg SeedFavoritesFromRoleDefaultsParams) error
	SoftDeleteService(ctx context.Context, id pgtype.UUID) (int64, error)
	UpdateAnnouncement(ctx context.Context, arg UpdateAnnouncementParams) (Announcement, error)
	UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error)
	// Display prefs persist server-side so they follow the user across devices.
	UpdateUserPrefs(ctx context.Context, arg UpdateUserPrefsParams) (User, error)
	// Called on every login: insert the OIDC subject or refresh the mutable fields.
	// primary_role and is_admin are re-derived from claims each login (docs/02 §6);
	// user prefs (view_mode, theme) are intentionally not touched here.
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
