// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search_events.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSearchEventsBefore = `-- name: DeleteSearchEventsBefore :execrows
delete from search_events where created_at < $1
`

// Retention pruning: drop events older than a cutoff (run from ops/a scheduled job).
func (q *Queries) DeleteSearchEventsBefore(ctx context.Context, cutoff pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSearchEventsBefore, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertSearchEvent = `-- name: InsertSearchEvent :exec
insert into search_events (query_norm, result_count) values ($1, $2)
`

type InsertSearchEventParams struct {
	QueryNorm   string `json:"query_norm"`
	ResultCount int32  `json:"result_count"`
}

// Append one search to the log (best-effort; never blocks the search response).
func (q *Queries) InsertSearchEvent(ctx context.Context, arg InsertSearchEventParams) error {
	_, err := q.db.Exec(ctx, insertSearchEvent, arg.QueryNorm, arg.ResultCount)
	return err
}

const listZeroResultSearches = `-- name: ListZeroResultSearches :many
select query_norm, count(*) as searches, max(created_at)::timestamptz as last_seen
from search_events
where result_count = 0 and created_at >= now() - make_interval(days => $1::int)
group by query_norm
order by searches desc, last_seen desc
limit $2
`

type ListZeroResultSearchesParams struct {
	Days int32 `json:"days"`
	Lim  int32 `json:"lim"`
}

type ListZeroResultSearchesRow struct {
	QueryNorm string             `json:"query_norm"`
	Searches  int64              `json:"searches"`
	LastSeen  pgtype.Timestamptz `json:"last_seen"`
}

// Most-searched queries that returned nothing within the last @days days — the
// admin worklist for adding keywords (docs/01 §4.6). Aggregate-only.
func (q *Queries) ListZeroResultSearches(ctx context.Context, arg ListZeroResultSearchesParams) ([]ListZeroResultSearchesRow, error) {
	rows, err := q.db.Query(ctx, listZeroResultSearches, arg.Days, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListZeroResultSearchesRow{}
	for rows.Next() {
		var i ListZeroResultSearchesRow
		if err := rows.Scan(&i.QueryNorm, &i.Searches, &i.LastSeen); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
