// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const frequentServiceIDs = `-- name: FrequentServiceIDs :many
select ce.service_id
from click_events ce
join services s on s.id = ce.service_id
where ce.user_id = $1 and ce.clicked_at >= $2 and s.is_active = true
group by ce.service_id
order by count(*) desc, max(ce.clicked_at) desc
limit $3
`

type FrequentServiceIDsParams struct {
	UserID pgtype.UUID        `json:"user_id"`
	Since  pgtype.Timestamptz `json:"since"`
	Lim    int32              `json:"lim"`
}

// The user's most-clicked active services within a rolling window, most-used
// first (powers "frequently used" — docs/01 §4.5).
func (q *Queries) FrequentServiceIDs(ctx context.Context, arg FrequentServiceIDsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, frequentServiceIDs, arg.UserID, arg.Since, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var service_id pgtype.UUID
		if err := rows.Scan(&service_id); err != nil {
			return nil, err
		}
		items = append(items, service_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordClick = `-- name: RecordClick :exec
insert into click_events (user_id, service_id, user_role)
values ($1, $2, $3)
`

type RecordClickParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ServiceID pgtype.UUID `json:"service_id"`
	UserRole  string      `json:"user_role"`
}

// A lightweight launch-click event (docs/01 §5.4). user_role is denormalized so
// aggregate metrics (Phase 4) need no join. NULLs on user/service delete keep
// history intact when a user or service is removed.
func (q *Queries) RecordClick(ctx context.Context, arg RecordClickParams) error {
	_, err := q.db.Exec(ctx, recordClick, arg.UserID, arg.ServiceID, arg.UserRole)
	return err
}
