// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const frequentServiceIDs = `-- name: FrequentServiceIDs :many
select ce.service_id
from click_events ce
join services s on s.id = ce.service_id
where ce.user_id = $1 and ce.clicked_at >= $2 and s.is_active = true
  and ce.target = 'service'
group by ce.service_id
order by count(*) desc, max(ce.clicked_at) desc
limit $3
`

type FrequentServiceIDsParams struct {
	UserID pgtype.UUID        `json:"user_id"`
	Since  pgtype.Timestamptz `json:"since"`
	Lim    int32              `json:"lim"`
}

// The user's most-clicked active services within a rolling window, most-used
// first (powers "frequently used" — docs/01 §4.5). Launches only (target =
// 'service'); a documentation-link click shouldn't promote a service here.
func (q *Queries) FrequentServiceIDs(ctx context.Context, arg FrequentServiceIDsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, frequentServiceIDs, arg.UserID, arg.Since, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var service_id pgtype.UUID
		if err := rows.Scan(&service_id); err != nil {
			return nil, err
		}
		items = append(items, service_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeOldClicks = `-- name: PurgeOldClicks :execrows
delete from click_events where clicked_at < $1
`

func (q *Queries) PurgeOldClicks(ctx context.Context, cutoff pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, purgeOldClicks, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordClick = `-- name: RecordClick :exec
insert into click_events (user_id, service_id, user_role, target)
values ($1, $2, $3, $4)
`

type RecordClickParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ServiceID pgtype.UUID `json:"service_id"`
	UserRole  string      `json:"user_role"`
	Target    string      `json:"target"`
}

// A lightweight click event (docs/01 §5.4). user_role is denormalized so
// aggregate metrics (Phase 4) need no join. target distinguishes a launch
// ('service') from a documentation-link click ('documentation'). NULLs on
// user/service delete keep history intact when a user or service is removed.
func (q *Queries) RecordClick(ctx context.Context, arg RecordClickParams) error {
	_, err := q.db.Exec(ctx, recordClick,
		arg.UserID,
		arg.ServiceID,
		arg.UserRole,
		arg.Target,
	)
	return err
}

const rollupClicks = `-- name: RollupClicks :exec
insert into usage_daily (day, service_id, user_role, target, clicks)
select date(clicked_at), service_id, user_role, target, count(*)
from click_events
where service_id is not null
group by date(clicked_at), service_id, user_role, target
on conflict (day, service_id, user_role, target) do update set clicks = excluded.clicks
`

// Recompute usage_daily from the raw events still present (the retention
// window). Idempotent: SET (not add). Days whose raw events have been purged are
// no longer recomputed, so their aggregate rows stay frozen at their last value.
func (q *Queries) RollupClicks(ctx context.Context) error {
	_, err := q.db.Exec(ctx, rollupClicks)
	return err
}
