// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByID = `-- name: GetUserByID :one
select id, oidc_sub, display_name, email, primary_role, is_admin, view_mode, theme, created_at, last_seen_at, favorites_order, favorites_separate_tab, favorites_seeded from users where id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OidcSub,
		&i.DisplayName,
		&i.Email,
		&i.PrimaryRole,
		&i.IsAdmin,
		&i.ViewMode,
		&i.Theme,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.FavoritesOrder,
		&i.FavoritesSeparateTab,
		&i.FavoritesSeeded,
	)
	return i, err
}

const getUserBySub = `-- name: GetUserBySub :one
select id, oidc_sub, display_name, email, primary_role, is_admin, view_mode, theme, created_at, last_seen_at, favorites_order, favorites_separate_tab, favorites_seeded from users where oidc_sub = $1
`

func (q *Queries) GetUserBySub(ctx context.Context, oidcSub string) (User, error) {
	row := q.db.QueryRow(ctx, getUserBySub, oidcSub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OidcSub,
		&i.DisplayName,
		&i.Email,
		&i.PrimaryRole,
		&i.IsAdmin,
		&i.ViewMode,
		&i.Theme,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.FavoritesOrder,
		&i.FavoritesSeparateTab,
		&i.FavoritesSeeded,
	)
	return i, err
}

const updateUserPrefs = `-- name: UpdateUserPrefs :one
update users
set view_mode              = $1,
    theme                  = $2,
    favorites_order        = $3,
    favorites_separate_tab = $4
where id = $5
returning id, oidc_sub, display_name, email, primary_role, is_admin, view_mode, theme, created_at, last_seen_at, favorites_order, favorites_separate_tab, favorites_seeded
`

type UpdateUserPrefsParams struct {
	ViewMode             string      `json:"view_mode"`
	Theme                string      `json:"theme"`
	FavoritesOrder       string      `json:"favorites_order"`
	FavoritesSeparateTab bool        `json:"favorites_separate_tab"`
	ID                   pgtype.UUID `json:"id"`
}

// Display prefs persist server-side so they follow the user across devices.
func (q *Queries) UpdateUserPrefs(ctx context.Context, arg UpdateUserPrefsParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPrefs,
		arg.ViewMode,
		arg.Theme,
		arg.FavoritesOrder,
		arg.FavoritesSeparateTab,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OidcSub,
		&i.DisplayName,
		&i.Email,
		&i.PrimaryRole,
		&i.IsAdmin,
		&i.ViewMode,
		&i.Theme,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.FavoritesOrder,
		&i.FavoritesSeparateTab,
		&i.FavoritesSeeded,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
insert into users (oidc_sub, display_name, email, primary_role, is_admin)
values ($1, $2, $3, $4, $5)
on conflict (oidc_sub) do update
set display_name = excluded.display_name,
    email        = excluded.email,
    primary_role = excluded.primary_role,
    is_admin     = excluded.is_admin,
    last_seen_at = now()
returning id, oidc_sub, display_name, email, primary_role, is_admin, view_mode, theme, created_at, last_seen_at, favorites_order, favorites_separate_tab, favorites_seeded
`

type UpsertUserParams struct {
	OidcSub     string      `json:"oidc_sub"`
	DisplayName string      `json:"display_name"`
	Email       pgtype.Text `json:"email"`
	PrimaryRole string      `json:"primary_role"`
	IsAdmin     bool        `json:"is_admin"`
}

// Called on every login: insert the OIDC subject or refresh the mutable fields.
// primary_role and is_admin are re-derived from claims each login (docs/02 §6);
// user prefs (view_mode, theme) are intentionally not touched here.
func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.OidcSub,
		arg.DisplayName,
		arg.Email,
		arg.PrimaryRole,
		arg.IsAdmin,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OidcSub,
		&i.DisplayName,
		&i.Email,
		&i.PrimaryRole,
		&i.IsAdmin,
		&i.ViewMode,
		&i.Theme,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.FavoritesOrder,
		&i.FavoritesSeparateTab,
		&i.FavoritesSeeded,
	)
	return i, err
}
